/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPRIMIR = 8;
  /** RegularExpression Id. */
  int SI = 9;
  /** RegularExpression Id. */
  int SINO = 10;
  /** RegularExpression Id. */
  int MIENTRAS = 11;
  /** RegularExpression Id. */
  int HACER = 12;
  /** RegularExpression Id. */
  int ASSIGN = 13;
  /** RegularExpression Id. */
  int PLUSASSIGN = 14;
  /** RegularExpression Id. */
  int MINUSASSIGN = 15;
  /** RegularExpression Id. */
  int MULASSIGN = 16;
  /** RegularExpression Id. */
  int DIVASSIGN = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MUL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int LBRACE = 24;
  /** RegularExpression Id. */
  int RBRACE = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int NUM = 27;
  /** RegularExpression Id. */
  int ID = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"imprimir\"",
    "\"si\"",
    "\"sino\"",
    "\"mientras\"",
    "\"hacer\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "<NUM>",
    "<ID>",
  };

}
