/* Generated By:JavaCC: Do not edit this line. Parser_practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser_practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int TABULACION = 2;
  /** RegularExpression Id. */
  int SALTO_LINEA = 3;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 4;
  /** RegularExpression Id. */
  int COMENTARIO_MULTI = 5;
  /** RegularExpression Id. */
  int PUNTO_COMA = 6;
  /** RegularExpression Id. */
  int PAREN_IZQ = 7;
  /** RegularExpression Id. */
  int PAREN_DER = 8;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 9;
  /** RegularExpression Id. */
  int LLAVE_DER = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int MAS_IGUAL = 12;
  /** RegularExpression Id. */
  int MENOS_IGUAL = 13;
  /** RegularExpression Id. */
  int MULT_IGUAL = 14;
  /** RegularExpression Id. */
  int DIV_IGUAL = 15;
  /** RegularExpression Id. */
  int SUMA = 16;
  /** RegularExpression Id. */
  int RESTA = 17;
  /** RegularExpression Id. */
  int MULT = 18;
  /** RegularExpression Id. */
  int DIV = 19;
  /** RegularExpression Id. */
  int IMPRIMIR = 20;
  /** RegularExpression Id. */
  int SI = 21;
  /** RegularExpression Id. */
  int SINO = 22;
  /** RegularExpression Id. */
  int MIENTRAS = 23;
  /** RegularExpression Id. */
  int HACER = 24;
  /** RegularExpression Id. */
  int ID = 25;
  /** RegularExpression Id. */
  int NUM = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "<TABULACION>",
    "<SALTO_LINEA>",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_MULTI>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"imprimir\"",
    "\"si\"",
    "\"sino\"",
    "\"mientras\"",
    "\"hacer\"",
    "<ID>",
    "<NUM>",
  };

}
