/* Parser_practica.java */
/* Generated By:JavaCC: Do not edit this line. Parser_practica.java */
// Definimos la clase Parser_practica
public class Parser_practica implements Parser_practicaConstants {

    // Definimos una variable estática para llevar un registro de las etiquetas generadas
    static int label=0;

    // Creamos un método para generar la siguiente etiqueta
    public static String siguiente_etiqueta(){
        return "LBL" + label++;     // Simplemente devuelve la cadena "LBL" seguida del numero actual para la etiqueta y luego incrementa el contador
    }

    // Creamos el main para ejecutar el parser
    public static void main(String args[]) throws ParseException, java.io.FileNotFoundException {

        // Instanciamos el parser
        Parser_practica parser;

        // Verificamos si se ha pasado un argumento al ejecutar el programa
        if ( args.length < 1 ) {
            // Si el argumento es menor que 1 significa que no se ha pasado ningín fichero, por lo que se utilizará la entrada estándar
            parser = new Parser_practica(System.in);
        } else {
            // Si se ha pasado un argumento, se utilizará el fichero del mismo como entrada
            parser = new Parser_practica(new java.io.FileInputStream(args[0]));
        }

        // Ejecuta el parser comenzando por el axioma, que corresponde a la producción list_sntncs
        parser.list_sntncs();
    }

// Definición de las producciones de la gramática

//Producción inicial que representa una lista de sentencias
  static final public void list_sntncs() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPRIMIR:
      case SI:
      case MIENTRAS:
      case HACER:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      sntnc();
      jj_consume_token(PUNTO_COMA);
    }
    jj_consume_token(0);
}

//Producción que representa una sentencia de cualquier tipo dentro de las contempladas en la gramática
  static final public void sntnc() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SI:{
      sel_stmt();
      break;
      }
    case MIENTRAS:
    case HACER:{
      iter_stmt();
      break;
      }
    case ID:{
      assig_stmt();
      break;
      }
    case IMPRIMIR:{
      print_stmt();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Producción que representa una sentencia de impresión
  static final public void print_stmt() throws ParseException {
    jj_consume_token(IMPRIMIR);
    jj_consume_token(PAREN_IZQ);
    expr();
    jj_consume_token(PAREN_DER);
System.out.println("\tprint");  //Imprime "print" al final de la sentencia

}

//Producción que representa una sentencia de selección (if-else)
  static final public void sel_stmt() throws ParseException {String lbl_Sal, lbl_else;   //Creamos dos variables para las etiquetas (lbl_Sal para la salida y lbl_else para el else)

    jj_consume_token(SI);
    jj_consume_token(PAREN_IZQ);
    expr();
    jj_consume_token(PAREN_DER);
lbl_else=siguiente_etiqueta();
        lbl_Sal=lbl_else;                               //Para el caso sin else, lbl_Sal es igual a lbl_else
        System.out.println("\tsifalsovea " + lbl_else); //Despues de evaluar la expresión, si es falsa salta a lbl_else

    jj_consume_token(LLAVE_IZQ);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPRIMIR:
      case SI:
      case MIENTRAS:
      case HACER:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      sntnc();
      jj_consume_token(PUNTO_COMA);
    }
    jj_consume_token(LLAVE_DER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINO:{
      jj_consume_token(SINO);
lbl_Sal=siguiente_etiqueta();                   //Si hay else, lbl_Sal es una nueva etiqueta
        System.out.println("\tvea " + lbl_Sal);         //Al final del if, salta a lbl_Sal para evitar ejecutar el else
        System.out.println(lbl_else);                   //Imprime lbl_else para comenzar el bloque else                   

      jj_consume_token(LLAVE_IZQ);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IMPRIMIR:
        case SI:
        case MIENTRAS:
        case HACER:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        sntnc();
        jj_consume_token(PUNTO_COMA);
      }
      jj_consume_token(LLAVE_DER);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
System.out.println(lbl_Sal);                    //Por ultimo imprimimos la etiqueta de salida, que en el caso de que haya else será distinta a la del else

}

//Producción que representa una sentencia de iteración (while o do-while)
  static final public void iter_stmt() throws ParseException {String lbl_Bucle,lbl_Salida;    //Creamos dos variables para las iteraciones, en el caso del do-while solo se usará lbl_Bucle

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MIENTRAS:{
      jj_consume_token(MIENTRAS);
lbl_Bucle=siguiente_etiqueta();
        lbl_Salida=siguiente_etiqueta();
        System.out.println(lbl_Bucle);  //Creamos las dos etiquetas y mostramos la etiqueta del bucle antes de evaluar la expresión para poder evaluarla al inicio de cada iteración

      jj_consume_token(PAREN_IZQ);
      expr();
      jj_consume_token(PAREN_DER);
System.out.println("\tsifalsovea " + lbl_Salida);   //Una vez evaluada la expresión, viajaremos a la etiqueta de salida si fuera falsa

      jj_consume_token(LLAVE_IZQ);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IMPRIMIR:
        case SI:
        case MIENTRAS:
        case HACER:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          break label_4;
        }
        sntnc();
        jj_consume_token(PUNTO_COMA);
      }
      jj_consume_token(LLAVE_DER);
System.out.println("\tvea " + lbl_Bucle);   //Una vez realizadas las acciones del bucle, volvemos a la etiqueta del bucle para reevaluar la expresión
        System.out.println(lbl_Salida); //Imprimimos la etiqueta de salida para cuando la condición del bucle sea falsa

      break;
      }
    case HACER:{
      jj_consume_token(HACER);
lbl_Bucle=siguiente_etiqueta();
        System.out.println(lbl_Bucle);  //Creamos la etiqueta del bucle, solo habrá una porque como evaluamos la condición al final, simplemente volveremos a esta etiqueta si fuera cierto y sino, continuariamos con el programa

      jj_consume_token(LLAVE_IZQ);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IMPRIMIR:
        case SI:
        case MIENTRAS:
        case HACER:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
        sntnc();
        jj_consume_token(PUNTO_COMA);
      }
      jj_consume_token(LLAVE_DER);
      jj_consume_token(MIENTRAS);
      jj_consume_token(PAREN_IZQ);
      expr();
      jj_consume_token(PAREN_DER);
System.out.println("\tsiciertovea " + lbl_Bucle);   //Evaluamos la expresión y si fuera cierta, volveriamos a la etiqueta del principio

      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Producción que representa una sentencia de asignación
  static final public void assig_stmt() throws ParseException {Token t;    //Creamos una variable de tipo Token para almacenar la entrada y poder imprimirla con image

    t = jj_consume_token(ID);
System.out.println("\tvalori " + t.image);  //Imprimimos el valori de la imagen del ID

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:{
      jj_consume_token(IGUAL);
      expr();
System.out.println("\tasigna");
      break;
      }
    case MAS_IGUAL:{
      jj_consume_token(MAS_IGUAL);
System.out.println("\tvalord " + t.image);
      expr();
System.out.println("\tsum");
        System.out.println("\tasigna");
      break;
      }
    case MENOS_IGUAL:{
      jj_consume_token(MENOS_IGUAL);
System.out.println("\tvalord " + t.image);
      expr();
System.out.println("\tsub");
        System.out.println("\tasigna");
      break;
      }
    case MULT_IGUAL:{
      jj_consume_token(MULT_IGUAL);
System.out.println("\tvalord " + t.image);
      expr();
System.out.println("\tmul");
        System.out.println("\tasigna");
      break;
      }
    case DIV_IGUAL:{
      jj_consume_token(DIV_IGUAL);
System.out.println("\tvalord " + t.image);
      expr();
System.out.println("\tdiv");
        System.out.println("\tasigna");
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Producción que representa una expresión aritmética de suma o resta
  static final public void expr() throws ParseException {
    mult_expr();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:
      case RESTA:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:{
        jj_consume_token(SUMA);
        mult_expr();
System.out.println("\tsum");//Al encontrar una suma, imprimimos dicha operación

        break;
        }
      case RESTA:{
        jj_consume_token(RESTA);
        mult_expr();
System.out.println("\tsub");//Lo mismo con la resta

        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

//Producción que representa una expresión aritmética de multiplicación o división
  static final public void mult_expr() throws ParseException {
    val();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DIV:{
        jj_consume_token(DIV);
        val();
System.out.println("\tdiv");//Al encontrar una división, imprimimos dicha operación

        break;
        }
      case MULT:{
        jj_consume_token(MULT);
        val();
System.out.println("\tmul");//Lo mismo con la multiplicación

        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

//Produccion que representa un valor, sea número, identificador o expresión entre paréntesis
  static final public void val() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM:{
      t = jj_consume_token(NUM);
System.out.println("\tmete " + t.image);//Imprimimos el mete con el valor del número

      break;
      }
    case ID:{
      t = jj_consume_token(ID);
System.out.println("\tvalord " + t.image);//Imprimimos el valord con el valor del identificador

      break;
      }
    case PAREN_IZQ:{
      jj_consume_token(PAREN_IZQ);
      expr();
      jj_consume_token(PAREN_DER);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public Parser_practicaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x3b00000,0x3b00000,0x3b00000,0x3b00000,0x400000,0x3b00000,0x3b00000,0x1800000,0xf800,0x30000,0x30000,0xc0000,0xc0000,0x6000080,};
	}

  /** Constructor with InputStream. */
  public Parser_practica(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser_practica(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new Parser_practicaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser_practica(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new Parser_practicaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new Parser_practicaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser_practica(Parser_practicaTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Parser_practicaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[27];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 27; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
