options {DEBUG_TOKEN_MANAGER=false;}


PARSER_BEGIN(Parser_practica)

public class Parser_practica {

    static int label=0;

    public static String siguiente_etiqueta(){
        return "LBL" + label++;
    }


    public static void main(String args[]) throws ParseException, java.io.FileNotFoundException {
        
        Parser_practica parser;

        if ( args.length < 1 ) {
            // Opción A: Entrada estándar
            parser = new Parser_practica(System.in);
        } else {
            // Opción B: Fichero
            parser = new Parser_practica(new java.io.FileInputStream(args[0]));
        }

        // Ejecuta el parser
        parser.list_sntncs();
    }
}

PARSER_END(Parser_practica)

// Definición de los tokenes que representan espacios en blanco y comentarios, que serán ignorados por el parser
SKIP :
{
    < ESPACIO: (" ")+ > |
    < TABULACION: ("\t")+ > |
    < SALTO_LINEA: ("\n")+ > |
    < COMENTARIO_LINEA: "//" (~["\n"])* > |
    < COMENTARIO_MULTI: "/*" (~["*"])* "*" ( ~["/"] (~["*"])* "*" )* "/" >
}

// Definición de los tokenes cuyas expresiones regulares contienen símbolos usados en la gramática
TOKEN:
{
    < PUNTO_COMA: ";" > |
    < PAREN_IZQ: "(" > |
    < PAREN_DER: ")" > |
    < LLAVE_IZQ: "{" > |
    < LLAVE_DER: "}" > |
    < IGUAL: "=" > |
    < MAS_IGUAL: "+=" > |
    < MENOS_IGUAL: "-=" > |
    < MULT_IGUAL: "*=" > |
    < DIV_IGUAL: "/=" > |
    < SUMA: "+" > |
    < RESTA: "-" > |
    < MULT: "*" > |
    < DIV: "/" >
}

// Definición de los tokenes cuyas expresiones regulares contienen palabras reservadas por la gramática
TOKEN:
{
    < IMPRIMIR: "imprimir" > |
    < SI: "si" > |
    < SINO: "sino" > |
    < MIENTRAS: "mientras" > |
    < HACER: "hacer" >
}

// Definición de los tokenes cuyas expresiones regulares contienen identificadores y números, axiomas de la gramática
TOKEN:
{
    < ID: ["a"-"z","A"-"Z","_"] (["a"-"z","A"-"Z","0"-"9","_"])* >   |
    < NUM: (["0"-"9"])+ >
}


void list_sntncs():
{}
{
    (sntnc() <PUNTO_COMA>)* <EOF>
}

void sntnc():
{}
{
    sel_stmt() | iter_stmt() | assig_stmt() | print_stmt()
}

void print_stmt():
{}
{
    <IMPRIMIR> <PAREN_IZQ> expr() <PAREN_DER>
    {
        System.out.println("\tprint");
    }
}


void sel_stmt():
{
    String lbl_Sal, lbl_else;
}
{
    <SI> <PAREN_IZQ> expr() <PAREN_DER> 
    {
        lbl_else=siguiente_etiqueta();
        lbl_Sal=lbl_else;
        System.out.println("\tsifalsovea " + lbl_else); 
    }
    <LLAVE_IZQ> ( sntnc() <PUNTO_COMA> )* <LLAVE_DER> 
    
    (<SINO> 
    {
        lbl_Sal=siguiente_etiqueta();
        System.out.println("\tvea " + lbl_Sal);
        System.out.println(lbl_else);
    }
    <LLAVE_IZQ> ( sntnc() <PUNTO_COMA> )* <LLAVE_DER>)?

    {
        System.out.println(lbl_Sal);
    }
}


void iter_stmt():
{   
    String lbl_Bucle,lbl_Salida;
}
{
    (<MIENTRAS> 
    {
        lbl_Bucle=siguiente_etiqueta();
        lbl_Salida=siguiente_etiqueta();
        System.out.println(lbl_Bucle);
    }
    <PAREN_IZQ> expr() <PAREN_DER> 
    {
        System.out.println("\tsifalsovea " + lbl_Salida);
    }
    <LLAVE_IZQ> ( sntnc() <PUNTO_COMA> )* <LLAVE_DER>
    {
        System.out.println("\tvea " + lbl_Bucle);
        System.out.println(lbl_Salida);
    }
    
    )
    | (<HACER> 
    {
        lbl_Bucle=siguiente_etiqueta();
        System.out.println(lbl_Bucle);
    }
    
    <LLAVE_IZQ> ( sntnc() <PUNTO_COMA> )* <LLAVE_DER> <MIENTRAS> <PAREN_IZQ> expr() <PAREN_DER> 
    {
        System.out.println("\tsiciertovea " + lbl_Bucle);
    }
    
    )
}


void assig_stmt():
{
    Token t;
}
{
    t = <ID> 
    {
        System.out.println("\tvalori " + t.image);
    }
    (<IGUAL> expr() 
    {
        System.out.println("\tasigna");
    }
    | <MAS_IGUAL> 
    {
        System.out.println("\tvalord " + t.image);
    }
    expr() 
    {
        System.out.println("\tsum");
        System.out.println("\tasigna");
    }
    | <MENOS_IGUAL> 
    {
        System.out.println("\tvalord " + t.image);
    }
    expr() 
    {
        System.out.println("\tsub");
        System.out.println("\tasigna");
    }
    | <MULT_IGUAL> 
    {
        System.out.println("\tvalord " + t.image);
    }
    expr() 
    {
        System.out.println("\tmul");
        System.out.println("\tasigna");
    }
    | <DIV_IGUAL> 
    {
        System.out.println("\tvalord " + t.image);
    }
    expr()
    {
        System.out.println("\tdiv");
        System.out.println("\tasigna");
    }
    )
}

void expr():
{}
{
    mult_expr() (<SUMA> mult_expr() 
    {
        System.out.println("\tsum ");
    }
    | <RESTA> mult_expr()
    {
        System.out.println("\tsub ");
    }
    )*
}

void mult_expr():
{}
{
    val() ( <DIV> val() 
    {
        System.out.println("\tdiv ");

    }
    | <MULT> val()
    {
        System.out.println("\tmul ");
    }
    )*
}

void val():
{
    Token t;
}
{
    t = <NUM> 
    {
        System.out.println("\tmete " + t.image);
    }
    |
    t= <ID> 
    {
        System.out.println("\tvalord " + t.image);
    }
    |
    <PAREN_IZQ> expr() <PAREN_DER>
}

